theodorusclarence/theodorusclarence.com

- context/PreloadContext.jsx
- hooks/useLoadingWithPreload.jsx
- pages/_app.js
- pages/_document.js
- pages/about.jsx
- pages/blog/index.jsx
- pages/index.jsx
- pages/library/index.jsx
- pages/projects.jsx
- styles/globals.css
add timeout when is not preloaded to compensate the preload overlay
but don't add timeout if already preloaded
> use-css-transform

- src/contents/blog/react-loading-state-pattern.mdx
- src/contents/library/toast.mdx
- src/pages/index.tsx
- feat(lib): add component and hooks to toast
- feat(blog): add react-loading-state-pattern
- feat: use separate variable for intro post
> toast pattern

- cypress/fixtures/spotify/not-playing.json
- cypress/fixtures/spotify/playing.json
- cypress/integration/features/spotify.spec.ts
- cypress/integration/pages/about.spec.ts
- cypress/integration/pages/blog.spec.ts
- cypress/integration/pages/index.spec.ts
- cypress/integration/pages/library.spec.ts
- cypress/integration/pages/projects.spec.ts
- cypress/integration/pages/subscribe.spec.ts
- cypress/integration/pages/trf.spec.ts
- src/components/layout/Spotify.tsx
- test: add spotify spec
- test: disable umami before each tests
> cypress feat

- src/components/layout/Footer.tsx
- src/components/layout/Layout.tsx
- src/constants/env.ts
- src/pages/guestbook.tsx
- feat: add sayHelloFlag
- feat: add guestbook
> guestbook landing

- src/components/TechStack.tsx
- src/components/links/ButtonLink.tsx
- src/pages/about.tsx
- src/pages/guestbook.tsx
- src/pages/index.tsx
- tailwind.config.js
- feat: add description to guestbook Seo
- feat: revamp landing and about page
> revamp landing

- src/pages/blog/[slug].tsx
- src/pages/library/[slug].tsx
- src/pages/projects/[slug].tsx
happens if navigating using `Link` from previous slug
> fix: table of contents not updating

- src/contents/blog/id-tailwindcss-best-practice.mdx
- src/contents/blog/tailwindcss-best-practice.mdx
> fix: mdx date broke safari

- src/components/Seo.tsx
- src/lib/helper.ts
- src/pages/blog/[slug].tsx
> feat: add custom blog og

- commitlint.config.js
- src/components/images/CloudinaryImg.tsx
- src/contents/projects/seasforus.mdx
- src/pages/index.tsx
- feat(proj): add seasforus
- ci: add commitlint scope-enum
- Resolve #216
> i216 seasforus project

- package.json
- src/components/content/CustomCode.tsx
- src/components/content/blog/BlogCard.tsx
- src/components/content/blog/Quiz.tsx
- src/components/content/library/LibraryCard.tsx
- src/pages/about.tsx
- src/pages/blog/[slug].tsx
- src/pages/library/[slug].tsx
- src/pages/projects/[slug].tsx
- src/styles/mdx.css
- tailwind.config.js
- yarn.lock
- feat: add whitespace to cards
- chore: update to tailwindcss v3
- refactor: use prose-invert for typography
- chore: update browserslist
> cards spacing

- src/components/content/Tag.tsx
- src/components/content/blog/BlogCard.tsx
- src/components/layout/Header.tsx
- src/components/layout/Layout.tsx
- src/pages/blog.tsx
- src/pages/library.tsx
- feat: add skip nav
- feat: add skip tags
> add skip nav

- package.json
- src/components/ReactTable.tsx
- src/components/Tooltip.tsx
- src/components/layout/Footer.tsx
- src/hooks/useContentMeta.tsx
- src/lib/contentMeta.ts
- src/pages/api/content/[slug].ts
- src/pages/blog/[slug].tsx
- src/pages/statistics.tsx
- src/styles/globals.css
- src/types/fauna.ts
- src/types/react-table.d.ts
- yarn.lock
- feat: add devtoViews tooltip
- feat: add statistics page
- Resolve #229
> i229 add devto details

- src/components/ReactTable.tsx
- src/pages/statistics.tsx
- refactor: use Cell for column declaration
- feat: add filter to statistics
> refactor table

- src/components/ReactTable.tsx
- src/pages/statistics.tsx
- feat: add footer total to statistics
- feat: add statistic cards
- Resolve #232
> i232 add total statistics

- src/constants/env.ts
- src/pages/_app.tsx
- src/pages/blog/[slug].tsx
- src/pages/dev/[pw].tsx
- fix: giscus not rerendering when changing route
- feat: add copywrite and status for dev
- feat: block increment views except on main domain
- Resolve #214
> i214 giscus not re rendering when navigating with <link>

- src/components/links/ButtonLink.tsx
- src/components/links/ShareTweetButton.tsx
- src/contents/blog/2021-retrospective.mdx
- src/contents/projects/love4heroes.mdx
- src/contents/projects/petrolida-2021.mdx
- src/contents/projects/ppdbsumsel.mdx
- src/contents/projects/seasforus.mdx
- src/contents/projects/sxceosleague.mdx
- src/contents/projects/tutee-id.mdx
- src/pages/blog/[slug].tsx
- src/pages/index.tsx
- feat(blog): add 2021-retrospective
- fix: tech icons on project have discs
> 2021 retro

- .vscode/typescriptreact.code-snippets
- package.json
- src/components/content/MDXComponents.tsx
- src/components/content/TweetCard.tsx
- src/components/content/card/GithubCard.tsx
- src/contents/blog/one-stop-starter.mdx
- src/pages/blog/[slug].tsx
- src/pages/index.tsx
- src/styles/globals.css
- yarn.lock
> twitter embed & one-stop-starter

- src/contents/projects/seasforus.mdx
backend deployment is no longer active
> feat: remove seasforus link deployment

- src/contents/library/sticky-nav.mdx
> fix(lib): sticky-nav demo won't load

- .eslintrc.js
- src/components/ReactTable.tsx
- src/pages/statistics.tsx
- feat: add right align to the statistics table
- feat: add stat card count
> table align

- .env.example
> docs: update and add comment to env example

- cypress/integration/features/spotify.spec.ts
> test: wait for spotify page to load

- src/components/buttons/Button.tsx
- src/components/content/blog/BlogCard.tsx
- src/components/content/library/LibraryCard.tsx
- src/components/content/projects/ProjectCard.tsx
- src/components/links/ButtonLink.tsx
- src/styles/globals.css
> feat: add motion safe animation

- package.json
- src/contents/projects/ppdbsumsel.mdx
- src/contents/projects/side-projects.mdx
- src/pages/_app.tsx
- yarn.lock
> fix: projects can't be opened on ios

- .eslintrc.js
- .vscode/typescriptreact.code-snippets
- package.json
- src/components/ColorSwatch.tsx
- src/components/buttons/ThemeButton.tsx
- src/components/layout/Footer.tsx
- src/components/layout/Header.tsx
- src/constants/env.ts
- src/pages/api/newsletter/add.ts
- src/pages/design.tsx
- src/styles/globals.css
- src/types/react-table.d.ts
- tailwind.config.js
- yarn.lock
- chore: upgrade to tailwindcss@3.1
- chore: hide feedback on development
- feat: add design page
- chore: add eslint unused import autofix
> design palette

- .github/workflows/lint.yml
- .github/workflows/release-please.yml
- package.json
- src/contents/projects/notiolink.mdx
- src/pages/index.tsx
- yarn.lock
- feat(proj): add notiolink
- ci: update lint and release
- Resolve #307
> i307 add notiolink and ppdb sulsel

- src/components/images/CloudinaryImg.tsx
- src/contents/projects/love4heroes.mdx
- src/contents/projects/notiolink.mdx
- src/contents/projects/petrolida-2021.mdx
- src/contents/projects/ppdbsumsel.mdx
- src/contents/projects/seasforus.mdx
- src/contents/projects/side-projects.mdx
- src/contents/projects/sxceosleague.mdx
- src/contents/projects/tutee-id.mdx
- feat: change image shadow from sm to default
- fix: mdx class isn't using className syntax
> mdx shadow

- src/contents/library/conventional-commit-readme.mdx
> fix: typo in conventional-commit-readme english part

- package.json
- src/pages/api/content/[slug].ts
- src/pages/api/like/[slug].ts
- src/pages/api/newsletter/add.ts
- src/pages/api/newsletter/count.ts
- src/pages/api/spotify.ts
- yarn.lock
- feat: add zod validation for api param
- feat: test spotify api
- Resolve #323
> i323 cache header & zod schema

- .env.example
- package.json
- src/components/content/Comment.tsx
- src/components/layout/Footer.tsx
- src/pages/_app.tsx
- yarn.lock
so other who forked this repo can immediately change the env
> feat: move public id to env

- .eslintrc.js
- next.config.js
- package.json
- src/contents/library/nextjs/mdx-hot-reload.mdx
- src/pages/_app.tsx
- yarn.lock
- chore: add mdx hot reload
- feat: add mdx-hot-reload shorts
> revamp posts

- src/contents/blog/nextjs-fetch-method.mdx
- src/contents/library/nextjs/mdx-hot-reload.mdx
- src/styles/mdx.css
- feat: add more context to mdx-hot-reload
- feat: update nextjs-fetch-method
- feat: change code highlight words color
> update fetch method
